services:
  - type: web
    name: fatigue-detection-system
    env: python
    plan: free
    buildCommand: pip install -r requirements_lightweight.txt
    startCommand: python simple_test.py
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12